/**********************************************************************************************************************
 * \file uds.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "App_Uds.h"
#include "App_Flash.h"
#include "IfxScuRcu.h"
#include <string.h>
#include "lwip/opt.h"
#include "App_Sota.h"
#include "FreeRTOS.h"
#include "task.h"

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
static uint8  g_session      = UDS_SESSION_DEFAULT;
static uint32 g_downloadAddr = 0;
static uint32 g_downloadSize = 0;
static uint32 g_writtenBytes = 0;
static uint8  g_blockSeq     = 0x01;   /* TransferData 순서 카운터 */
static uint32  g_crcAddr     = 0;
static uint32  g_crcSize     = 0;
static boolean g_crcPending  = FALSE;
static uint32  g_erasedUntil = 0;    /* next non-erased sector start, non-cached address */

static IfxFlash_FlashType UDS_GetFlashTypeByAddr(uint32 addr)
{
    uint32 a = TO_FLASH_ADDR(addr);

    if ((a >= 0xA0000000UL) && (a < 0xA0300000UL))
    {
        return IfxFlash_FlashType_P0;
    }

    if ((a >= 0xA0300000UL) && (a < 0xA0600000UL))
    {
        return IfxFlash_FlashType_P1;
    }

    /* TC375 6MB SOTA 영역 밖이면 일단 P1로 떨어뜨리지 말고 호출부에서 주소 범위를 먼저 막는 것이 안전하다. */
    return IfxFlash_FlashType_P0;
}

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
static uint16 UDS_NegResponse       (uint8 *tx, uint8 sid, uint8 nrc);
static uint16 UDS_SessionControl    (uint8 *rx, uint16 rxLen, uint8 *tx);
static uint16 UDS_RequestDownload   (uint8 *rx, uint16 rxLen, uint8 *tx);
static uint16 UDS_TransferData      (uint8 *rx, uint16 rxLen, uint8 *tx);
static uint16 UDS_TransferExit      (uint8 *rx, uint16 rxLen, uint8 *tx);

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
void AppUds_Task(void *arg)
{
    (void)arg;

    for(;;)
    {
        if (g_crcPending)
        {
            g_crcPending = FALSE;
            vTaskDelay(pdMS_TO_TICKS(APP_UDS_TASK_PERIOD_MS));
            IfxScuRcu_performReset(IfxScuRcu_ResetType_system, 0);
        }
        vTaskDelay(pdMS_TO_TICKS(APP_UDS_TASK_PERIOD_MS));
    }
}

/* ── 외부 진입점 ────────────────────────────────────────────── */
void UDS_HandleService(uint8  *rxData, uint16  rxLen,
                       uint8  *txData, uint16 *txLen)
{
    if (rxLen == 0)
    {
        *txLen = 0;
        return;
    }

    uint8 sid = rxData[0];

    switch (sid)
    {
        case UDS_SID_SESSION_CONTROL:
            *txLen = UDS_SessionControl(rxData, rxLen, txData);
            break;

        case UDS_SID_REQUEST_DOWNLOAD:
            *txLen = UDS_RequestDownload(rxData, rxLen, txData);
            break;

        case UDS_SID_TRANSFER_DATA:
            *txLen = UDS_TransferData(rxData, rxLen, txData);
            break;

        case UDS_SID_TRANSFER_EXIT:
            *txLen = UDS_TransferExit(rxData, rxLen, txData);
            break;

        default:
            *txLen = UDS_NegResponse(txData, sid,
                                     UDS_NRC_SERVICE_NOT_SUPPORTED);
            break;
    }
}

/* ── 부정 응답 생성 ─────────────────────────────────────────── */
static uint16 UDS_NegResponse(uint8 *tx, uint8 sid, uint8 nrc)
{
    tx[0] = UDS_NEGATIVE_RSP;   /* 0x7F */
    tx[1] = sid;
    tx[2] = nrc;
    return 3;
}

/* ── 0x10 DiagnosticSessionControl ─────────────────────────── */
/*
 * 요청: [0x10] [세션타입]
 * 응답: [0x50] [세션타입] [P2_hi] [P2_lo] [P2ex_hi] [P2ex_lo]
 */
static uint16 UDS_SessionControl(uint8 *rx, uint16 rxLen, uint8 *tx)
{
    if (rxLen < 2)
        return UDS_NegResponse(tx, UDS_SID_SESSION_CONTROL,
                               UDS_NRC_GENERAL_REJECT);

    uint8 reqSession = rx[1];

    if (reqSession == UDS_SESSION_DEFAULT ||
        reqSession == UDS_SESSION_EXTENDED)
    {
        g_session = reqSession;

        tx[0] = UDS_SID_SESSION_CONTROL + UDS_POS_RESPONSE_OFFSET; /* 0x50 */
        tx[1] = reqSession;
        tx[2] = 0x00; tx[3] = 0x19;    /* P2 = 25ms  */
        tx[4] = 0x01; tx[5] = 0xF4;    /* P2* = 500ms */
        return 6;
    }

    return UDS_NegResponse(tx, UDS_SID_SESSION_CONTROL,
                           UDS_NRC_SUBFUNC_NOT_SUPPORTED);
}

/* ── 0x34 RequestDownload ───────────────────────────────────── */
/*
 * 요청: [0x34] [dataFormatId] [addrAndLenFormatId]
 *              [memAddr x N바이트] [memSize x M바이트]
 * 응답: [0x74] [lengthFormatId] [maxBlockSize_hi] [maxBlockSize_lo]
 */
static uint16 UDS_RequestDownload(uint8 *rx, uint16 rxLen, uint8 *tx)
{
    if (g_session != UDS_SESSION_EXTENDED)
        return UDS_NegResponse(tx, UDS_SID_REQUEST_DOWNLOAD,
                               UDS_NRC_CONDITIONS_NOT_CORRECT);

    if (rxLen < 4)
        return UDS_NegResponse(tx, UDS_SID_REQUEST_DOWNLOAD,
                               UDS_NRC_GENERAL_REJECT);

    /* addrAndLengthFormatIdentifier 파싱
       하위 니블 = 주소 바이트 수
       상위 니블 = 크기 바이트 수  */
    uint8 addrLen = (rx[2] >> 0) & 0x0F;
    uint8 sizeLen = (rx[2] >> 4) & 0x0F;

    if (rxLen < (uint16)(3 + addrLen + sizeLen))
        return UDS_NegResponse(tx, UDS_SID_REQUEST_DOWNLOAD,
                               UDS_NRC_GENERAL_REJECT);

    if (SOTA_IsGroupBActive())
        g_downloadAddr = 0x80020000UL;  /* inactive = Bank A */
    else
        g_downloadAddr = 0x80320000UL;  /* inactive = Bank B */        

    /* 메모리 크기 파싱 */
    g_downloadSize = 0;
    for (uint8 i = 0; i < sizeLen; i++)
        g_downloadSize = (g_downloadSize << 8) | rx[3 + addrLen + i];

    /* 상태 초기화 */
    g_writtenBytes = 0;
    g_blockSeq     = 0x01;

    /*
     * 여기서 전체 App 영역을 한 번에 erase하지 않는다.
     * 3MB를 RequestDownload 안에서 모두 지우면 DoIP/UDS 응답이 timeout 될 수 있다.
     * 공식 예제처럼 TransferData 진행 중 필요한 sector만 on-demand erase한다.
     */
    uint32 flashStart = TO_FLASH_ADDR(g_downloadAddr);
    uint32 flashEnd   = flashStart + g_downloadSize;

    /* TC375 SOTA 대상 범위 보호: Bank A/B 6MB 밖으로 쓰지 않도록 차단 */
    if ((flashStart < 0xA0000000UL) || (flashEnd > 0xA0600000UL) || (flashEnd <= flashStart))
    {
        return UDS_NegResponse(tx, UDS_SID_REQUEST_DOWNLOAD,
                               UDS_NRC_REQUEST_OUT_OF_RANGE);
    }

    g_erasedUntil = flashStart & ~(PFLASH_SECTOR_SIZE - 1U);

    /* 긍정 응답 */
    tx[0] = UDS_SID_REQUEST_DOWNLOAD + UDS_POS_RESPONSE_OFFSET; /* 0x74 */
    tx[1] = 0x20;                               /* lengthFormatIdentifier: 2바이트 크기 */
    // tx[2] = (MAX_BLOCK_SIZE >> 8) & 0xFF;
    // tx[3] =  MAX_BLOCK_SIZE       & 0xFF;
    tx[2] = 0x02;   /* 고정값 */
    tx[3] = 0x02;   /* 0x0202 = 514 → chunk = 512 = 16×32 정렬 */    
    return 4;
}

/* ── 0x36 TransferData ──────────────────────────────────────── */
/*
 * 요청: [0x36] [blockSeqCounter] [data...]
 * 응답: [0x76] [blockSeqCounter]
 */
static uint16 UDS_TransferData(uint8 *rx, uint16 rxLen, uint8 *tx)
{
    if (g_downloadSize == 0)
        return UDS_NegResponse(tx, UDS_SID_TRANSFER_DATA,
                               UDS_NRC_CONDITIONS_NOT_CORRECT);

    if (rxLen < 2)
        return UDS_NegResponse(tx, UDS_SID_TRANSFER_DATA,
                               UDS_NRC_GENERAL_REJECT);

    /* 순서 카운터 확인 */
    uint8 seqCounter = rx[1];
    if (seqCounter != g_blockSeq)
        return UDS_NegResponse(tx, UDS_SID_TRANSFER_DATA,
                               UDS_NRC_WRONG_BLOCK_SEQ_COUNTER);

    uint8  *chunk    = rx + 2;
    uint16  chunkLen = rxLen - 2;

    if (chunkLen == 0 || chunkLen > MAX_BLOCK_SIZE)
        return UDS_NegResponse(tx, UDS_SID_TRANSFER_DATA,
                               UDS_NRC_REQUEST_OUT_OF_RANGE);

    /* Flash Write: 필요한 sector를 먼저 하나씩 erase한 뒤 write한다. */
    uint32 curAddr    = g_downloadAddr + g_writtenBytes;
    uint32 writeStart = TO_FLASH_ADDR(curAddr);
    uint32 writeEnd   = writeStart + chunkLen;

    if ((writeStart < 0xA0000000UL) || (writeEnd > 0xA0600000UL) || (writeEnd <= writeStart))
    {
        return UDS_NegResponse(tx, UDS_SID_TRANSFER_DATA,
                               UDS_NRC_REQUEST_OUT_OF_RANGE);
    }

    while (writeEnd > g_erasedUntil)
    {
        IfxFlash_FlashType eraseType = UDS_GetFlashTypeByAddr(g_erasedUntil);

        if (!OTA_Flash_Erase(g_erasedUntil, PFLASH_SECTOR_SIZE, eraseType))
        {
            return UDS_NegResponse(tx, UDS_SID_TRANSFER_DATA,
                                   UDS_NRC_GENERAL_PROG_FAILURE);
        }

        g_erasedUntil += PFLASH_SECTOR_SIZE;
    }

    IfxFlash_FlashType flashType = UDS_GetFlashTypeByAddr(curAddr);
    boolean ok = OTA_Flash_Write(curAddr, chunk, chunkLen, flashType);

    if (!ok)
        return UDS_NegResponse(tx, UDS_SID_TRANSFER_DATA,
                               UDS_NRC_GENERAL_PROG_FAILURE);

    g_writtenBytes += chunkLen;

    /* 순서 카운터 증가 (0xFF → 0x00 으로 롤오버) */
    g_blockSeq = (g_blockSeq >= 0xFF) ? 0x00 : g_blockSeq + 1;

    /* 긍정 응답 */
    tx[0] = UDS_SID_TRANSFER_DATA + UDS_POS_RESPONSE_OFFSET;  /* 0x76 */
    tx[1] = seqCounter;
    return 2;
}

/* ── 0x37 RequestTransferExit ───────────────────────────────── */
/*
 * 요청: [0x37]
 * 응답: [0x77]  → CRC OK 시
 * 이후: DFLASH 플래그 기록 → Soft Reset → Bootloader → 새 FW 부팅
 */
static uint16 UDS_TransferExit(uint8 *rx, uint16 rxLen, uint8 *tx)
{
    LWIP_UNUSED_ARG(rx);
    LWIP_UNUSED_ARG(rxLen);

    if (g_writtenBytes == 0)
        return UDS_NegResponse(tx, UDS_SID_TRANSFER_EXIT,
                               UDS_NRC_CONDITIONS_NOT_CORRECT);

    uint32 expectedCRC = ((uint32)rx[1] << 24) |
                         ((uint32)rx[2] << 16) |
                         ((uint32)rx[3] <<  8) |
                         ((uint32)rx[4]);                               

    g_crcAddr    = g_downloadAddr;
    g_crcSize    = g_writtenBytes;
    g_crcPending = TRUE;

    tx[0] = UDS_SID_TRANSFER_EXIT + UDS_POS_RESPONSE_OFFSET;  /* 0x77 */

    OTA_Flash_SetFlag(g_writtenBytes, expectedCRC);

    g_session      = UDS_SESSION_DEFAULT;
    g_downloadAddr = 0;
    g_downloadSize = 0;
    g_writtenBytes = 0;
    g_blockSeq     = 0x01;
    g_erasedUntil  = 0;

    return 1;
}

/*********************************************************************************************************************/
