/**********************************************************************************************************************
 * \file uds.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef APP_UDS_H_
#define APP_UDS_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "Ifx_Types.h"

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
// #define MAX_BLOCK_SIZE      512     /* TransferData 한 번에 받을 최대 바이트 */
#define MAX_BLOCK_SIZE      514     /* TransferData 한 번에 받을 최대 바이트 */
#define UDS_NEGATIVE_RSP    0x7F

#define UDS_SID_SESSION_CONTROL     0x10
#define UDS_SID_REQUEST_DOWNLOAD    0x34
#define UDS_SID_TRANSFER_DATA       0x36
#define UDS_SID_TRANSFER_EXIT       0x37

/* ── 세션 타입 ─────────────────────────────────────────────── */
#define UDS_SESSION_DEFAULT         0x01
#define UDS_SESSION_EXTENDED        0x03

/* ── 긍정 응답 SID ─────────────────────────────────────────── */
#define UDS_POS_RESPONSE_OFFSET     0x40   /* 요청 SID + 0x40 = 긍정응답 */

/* ── 부정 응답 코드 (NRC) ──────────────────────────────────── */
#define UDS_NRC_GENERAL_REJECT              0x10
#define UDS_NRC_SERVICE_NOT_SUPPORTED       0x11
#define UDS_NRC_SUBFUNC_NOT_SUPPORTED       0x12
#define UDS_NRC_CONDITIONS_NOT_CORRECT      0x22
#define UDS_NRC_REQUEST_OUT_OF_RANGE        0x31
#define UDS_NRC_WRONG_BLOCK_SEQ_COUNTER     0x73
#define UDS_NRC_GENERAL_PROG_FAILURE        0x72

#define APP_UDS_TASK_STACK_SIZE              (256u)
#define APP_UDS_TASK_PRIORITY                (tskIDLE_PRIORITY + 5u)
#define APP_UDS_TASK_PERIOD_MS               (50u)

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
extern volatile uint32 g_TickCount_1ms;   /* Ifx_Lwip.c에 정의됨 */

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
void AppUds_Task(void *arg);
void UDS_HandleService(uint8  *rxData,   uint16  rxLen,
                       uint8  *txData,   uint16 *txLen);

/*********************************************************************************************************************/


#endif /* APP_UDS_H_ */
