/**********************************************************************************************************************
 * \file bootloader.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "bootloader.h"
#include "ota_flash.h"
#include "sota_ucb.h"
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
typedef void (*AppFunc)(void);
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/

static void Bootloader_JumpToApp(uint32 appAddr)
{
    AppFunc app = (AppFunc)appAddr;
    app();
}

void Bootloader_Main(void)
{
    //OTA flag 확인
    uint32 flag = *(volatile uint32 *)OTA_FLAG_ADDR;
    //SOTA 초기화 여부 확인
    if (!SOTA_IsInitialized())
    {
        SOTA_InitialSetup();
        while (1) {}
    }

    //OTA 플래그가 설정된 경우 → OTA 검증 → 그룹 스왑 → 새 FW 부팅
    
    if (flag == OTA_FLAG_MAGIC)
    {
        uint32 fwSize     = *(volatile uint32 *)(OTA_FLAG_ADDR + 8);
        uint32 expectedCRC = *(volatile uint32 *)(OTA_FLAG_ADDR + 16);
        
        boolean isGroupBActive = SOTA_IsGroupBActive();

        uint32 targetStart = isGroupBActive ? BANK_A_START : BANK_B_START;
        uint32 targetSize  = isGroupBActive ? BANK_A_SIZE  : BANK_B_SIZE;

        // 검증 성공 시 Group B로 스왑, 실패 시 Group A로 스왑 
        if ((fwSize > 0) &&
            (fwSize <= targetSize) &&
            OTA_Flash_VerifyCRC(targetStart, fwSize, expectedCRC))
        {
            OTA_Flash_ClearFlag();

            if (isGroupBActive)
                SOTA_SwapToGroupA();
            else
                SOTA_SwapToGroupB();

            Bootloader_JumpToApp(APP_START_ADDR);
        }
        // 검증 실패 시 → 플래그 클리어 → Group A로 스왑 (복구 시나리오) → 새 FW 부팅
        else
        {
            OTA_Flash_ClearFlag();

            if (SOTA_IsGroupBActive())
                SOTA_SwapToGroupA();
            else
                    SOTA_SwapToGroupB();
                    
            Bootloader_JumpToApp(APP_START_ADDR);
        }
    }
    //OTA 플래그가 설정되지 않은 경우 → 정상 부팅
    else
    {
        Bootloader_JumpToApp(APP_START_ADDR);
    }
}
/*********************************************************************************************************************/
