/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Ifx_Cfg_Ssw.h"
#include "sota_ucb.h"
#include "ota_flash.h"
#include <stdio.h>
#include "IfxAsclin_Asc.h"
#include "IfxAsclin_reg.h"
#include "UART_VCOM.h"

boolean g_isGroupBActive = FALSE;
extern IfxAsclin_Asc g_ascPrint;

int _write(int fd, char *buf, int len)
{
    (void)fd;

    if ((buf == NULL_PTR) || (len <= 0))
        return 0;

    for (int i = 0; i < len; i++)
    {
        uint32 timeout = 1000000u;

        while ((IfxAsclin_getTxFifoFillLevel(&MODULE_ASCLIN0) >= 16u) && (timeout-- > 0u))
            __nop();

        if (timeout == 0u)
            break;

        IfxAsclin_writeTxData(&MODULE_ASCLIN0, (uint16)(uint8)buf[i]);
    }

    return len;
}

IFX_ALIGN(4) IfxCpu_syncEvent cpuSyncEvent = 0;
extern void Bootloader_Main(void);

void core1_main(void) { while(1) {} }
void core2_main(void) { while(1) {} }

void core0_main(void)
{
    // IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    init_UART();
    if (!SOTA_IsInitialized()) {
           SOTA_InitialSetup();
    }
    g_isGroupBActive = SOTA_IsGroupBActive();
    g_isGroupBActive ? printf("Bootloader Bank B!\r\n") : printf("Bootloader Bank A!\r\n");    

    for (int i = 0; i < 10000000; ++i);
    Bootloader_Main();

    while(1)
    {
    }
}