/**********************************************************************************************************************
 * \file doip.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef APP_DOIP_H_
#define APP_DOIP_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "Ifx_Types.h"

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
#define DOIP_PORT               13400
#define DOIP_HEADER_LEN         8
#define DOIP_PROTOCOL_VERSION   0x02
#define DOIP_RX_BUF_SIZE        4096

/* PayloadType */
#define DOIP_ROUTING_ACT_REQ    0x0005
#define DOIP_ROUTING_ACT_RES    0x0006
#define DOIP_DIAG_MESSAGE       0x8001
#define DOIP_DIAG_MESSAGE_ACK   0x8002

/* 논리 주소 */
#define DOIP_TESTER_ADDR        0x0E00   /* RPi */
#define DOIP_ZCU_ADDR           0x0001   /* ZCU */

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
enum DoIPStates
{
    DOIP_STATE_NONE = 0,
    DOIP_STATE_ACCEPTED,
    DOIP_STATE_ROUTING_ACTIVE,
    DOIP_STATE_CLOSING
};

typedef struct tcp_pcb tcpPcb;
typedef struct pbuf    pBuf;

typedef struct
{
    uint8    state;
    tcpPcb *pcb;
    pBuf   *p;
    uint8   rxBuf[DOIP_RX_BUF_SIZE];
    uint16  rxLen;
} DoIPSession;

/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
void DoIP_Init(void);
void DoIP_MainFunction(void);

/*********************************************************************************************************************/


#endif /* APP_DOIP_H_ */
