/**********************************************************************************************************************
 * \file doip.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "App_DoIP.h"
#include "App_Uds.h"
#include <string.h>
#include "lwip/opt.h"
#include "lwip/tcp.h"
#include "lwip/mem.h"

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
static tcpPcb *g_doipPcb;

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
static err_t  DoIP_Accept  (void *arg, tcpPcb *newPcb, err_t err);
static err_t  DoIP_Recv    (void *arg, tcpPcb *tpcb, pBuf *p, err_t err);
static void   DoIP_Error   (void *arg, err_t err);
static err_t  DoIP_Poll    (void *arg, tcpPcb *tpcb);
static void   DoIP_Close   (tcpPcb *tpcb, DoIPSession *ds);

static void   DoIP_Process (tcpPcb *tpcb, DoIPSession *ds);
static void   DoIP_HandleRoutingActivation (tcpPcb *tpcb, DoIPSession *ds, uint8 *payload);
static void   DoIP_HandleDiagMessage       (tcpPcb *tpcb, DoIPSession *ds,
                                            uint8 *payload, uint32 payloadLen);
static void   DoIP_SendRaw (tcpPcb *tpcb, uint8 *buf, uint16 len);
static void   DoIP_BuildHeader (uint8 *buf, uint16 payloadType, uint32 payloadLen);

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
void DoIP_Init(void)
{
    g_doipPcb = tcp_new();
    if (g_doipPcb != NULL)
    {
        err_t err = tcp_bind(g_doipPcb, IP_ADDR_ANY, DOIP_PORT);
        if (err == ERR_OK)
        {
            g_doipPcb = tcp_listen(g_doipPcb);
            tcp_accept(g_doipPcb, DoIP_Accept);
        }
    }
}

/* Echo.c echoAccept() 와 동일한 구조 */
static err_t DoIP_Accept(void *arg, tcpPcb *newPcb, err_t err)
{
    LWIP_UNUSED_ARG(arg);
    LWIP_UNUSED_ARG(err);

    DoIPSession *ds = (DoIPSession *)mem_malloc(sizeof(DoIPSession));
    if (ds == NULL)
        return ERR_MEM;

    ds->state = DOIP_STATE_ACCEPTED;
    ds->pcb   = newPcb;
    ds->p     = NULL;
    ds->rxLen = 0;
    memset(ds->rxBuf, 0, sizeof(ds->rxBuf));

    tcp_arg (newPcb, ds);
    tcp_recv(newPcb, DoIP_Recv);
    tcp_err (newPcb, DoIP_Error);
    tcp_poll(newPcb, DoIP_Poll, 2);

    return ERR_OK;
}

/* Echo.c echoRecv() 와 동일한 구조 */
static err_t DoIP_Recv(void *arg, tcpPcb *tpcb, pBuf *p, err_t err)
{
    DoIPSession *ds = (DoIPSession *)arg;

    /* 연결 종료 */
    if (p == NULL)
    {
        ds->state = DOIP_STATE_CLOSING;
        DoIP_Close(tpcb, ds);
        return ERR_OK;
    }

    if (err != ERR_OK)
    {
        pbuf_free(p);
        return err;
    }

    /* pbuf → rxBuf 복사 (Echo.c echoUnpack 역할) */
    uint16 copyLen = p->tot_len;
    if (copyLen > DOIP_RX_BUF_SIZE)
        copyLen = DOIP_RX_BUF_SIZE;

    pbuf_copy_partial(p, ds->rxBuf, copyLen, 0);
    ds->rxLen = copyLen;

    tcp_recved(tpcb, p->tot_len);   /* lwIP에 수신 완료 알림 */
    pbuf_free(p);

    /* DoIP 처리 */
    DoIP_Process(tpcb, ds);

    return ERR_OK;
}

/* Echo.c echoError() 와 동일한 구조 */
static void DoIP_Error(void *arg, err_t err)
{
    LWIP_UNUSED_ARG(err);
    DoIPSession *ds = (DoIPSession *)arg;
    if (ds != NULL)
        mem_free(ds);
}

/* Echo.c echoPoll() 와 동일한 구조 */
static err_t DoIP_Poll(void *arg, tcpPcb *tpcb)
{
    DoIPSession *ds = (DoIPSession *)arg;
    if (ds == NULL)
    {
        tcp_abort(tpcb);
        return ERR_ABRT;
    }
    if (ds->state == DOIP_STATE_CLOSING)
        DoIP_Close(tpcb, ds);

    return ERR_OK;
}

/* Echo.c echoClose() 와 동일한 구조 */
static void DoIP_Close(tcpPcb *tpcb, DoIPSession *ds)
{
    tcp_arg (tpcb, NULL);
    tcp_recv(tpcb, NULL);
    tcp_err (tpcb, NULL);
    tcp_poll(tpcb, NULL, 0);

    if (ds != NULL)
        mem_free(ds);

    tcp_close(tpcb);
}

/*********************************************************************************************************************/
/* DoIP 고유 처리 함수들                                                                                              */
/*********************************************************************************************************************/

/* DoIP 헤더 파싱 후 PayloadType 분기 */
static void DoIP_Process(tcpPcb *tpcb, DoIPSession *ds)
{
    uint8  *buf = ds->rxBuf;
    uint16  len = ds->rxLen;

    if (len < DOIP_HEADER_LEN)
        return;   /* 헤더도 안 왔으면 무시 */

    /* 헤더 파싱 */
    uint16 payloadType = ((uint16)buf[2] << 8) | buf[3];
    uint32 payloadLen  = ((uint32)buf[4] << 24) | ((uint32)buf[5] << 16)
                       | ((uint32)buf[6] <<  8) |  (uint32)buf[7];

    uint8 *payload = buf + DOIP_HEADER_LEN;

    switch (payloadType)
    {
        case DOIP_ROUTING_ACT_REQ:
            DoIP_HandleRoutingActivation(tpcb, ds, payload);
            break;

        case DOIP_DIAG_MESSAGE:
            DoIP_HandleDiagMessage(tpcb, ds, payload, payloadLen);
            break;

        default:
            break;
    }
}

/* Routing Activation 처리 */
static void DoIP_HandleRoutingActivation(tcpPcb *tpcb, DoIPSession *ds, uint8 *payload)
{
    /* 요청 페이로드에서 테스터 주소 읽기 */
    uint16 testerAddr = ((uint16)payload[0] << 8) | payload[1];

    uint8 res[21];
    DoIP_BuildHeader(res, DOIP_ROUTING_ACT_RES, 13);

    /* 요청에서 받은 주소 그대로 에코 */
    res[8]  = (testerAddr    >> 8) & 0xFF;
    res[9]  =  testerAddr          & 0xFF;
    res[10] = (DOIP_ZCU_ADDR >> 8) & 0xFF;
    res[11] =  DOIP_ZCU_ADDR       & 0xFF;
    res[12] = 0x10;   /* 성공 */
    res[13] = 0x00; res[14] = 0x00;
    res[15] = 0x00; res[16] = 0x00;  /* Reserved ISO */
    res[17] = 0x00; res[18] = 0x00;
    res[19] = 0x00; res[20] = 0x00;  /* Reserved OEM */

    DoIP_SendRaw(tpcb, res, sizeof(res));
    ds->state = DOIP_STATE_ROUTING_ACTIVE;
}

/* Diagnostic Message 처리 → UDS로 전달 */
static void DoIP_HandleDiagMessage(tcpPcb *tpcb, DoIPSession *ds,
                                   uint8 *payload, uint32 payloadLen)
{
    if (ds->state != DOIP_STATE_ROUTING_ACTIVE)
        return;

    /* payload[0~1]: 소스(tester), payload[2~3]: 타겟(ZCU) */
    uint16 srcAddr    = ((uint16)payload[0] << 8) | payload[1];
    uint16 targetAddr = ((uint16)payload[2] << 8) | payload[3];

    if (targetAddr != DOIP_ZCU_ADDR)
        return;

    /* ── Diag ACK: ZCU → Tester ──────────────────────────── */
    uint8 ack[13];
    DoIP_BuildHeader(ack, DOIP_DIAG_MESSAGE_ACK, 5);
    ack[8]  = (DOIP_ZCU_ADDR >> 8) & 0xFF;  /* source = ZCU   ← 수정 */
    ack[9]  =  DOIP_ZCU_ADDR       & 0xFF;
    ack[10] = (srcAddr       >> 8) & 0xFF;  /* target = Tester ← 수정 */
    ack[11] =  srcAddr             & 0xFF;
    ack[12] = 0x00;
    DoIP_SendRaw(tpcb, ack, sizeof(ack));

    /* ── UDS 처리 ─────────────────────────────────────────── */
    uint8  *udsData   = payload + 4;
    uint16  udsLen    = (uint16)(payloadLen - 4);
    uint8   udsRes[256];
    uint16  udsResLen = 0;

    UDS_HandleService(udsData, udsLen, udsRes, &udsResLen);

    /* ── UDS 응답을 DoIP로 감싸서 전송: ZCU → Tester ─────── */
    if (udsResLen > 0)
    {
        uint32 diagLen = 4 + udsResLen;
        uint8  res[DOIP_HEADER_LEN + 4 + 256];

        DoIP_BuildHeader(res, DOIP_DIAG_MESSAGE, diagLen);
        res[8]  = (DOIP_ZCU_ADDR >> 8) & 0xFF;  /* source = ZCU   */
        res[9]  =  DOIP_ZCU_ADDR       & 0xFF;
        res[10] = (srcAddr       >> 8) & 0xFF;  /* target = Tester */
        res[11] =  srcAddr             & 0xFF;
        memcpy(&res[12], udsRes, udsResLen);

        DoIP_SendRaw(tpcb, res, (uint16)(DOIP_HEADER_LEN + diagLen));
    }
}

/* DoIP 헤더 생성 */
static void DoIP_BuildHeader(uint8 *buf, uint16 payloadType, uint32 payloadLen)
{
    buf[0] = DOIP_PROTOCOL_VERSION;
    buf[1] = ~DOIP_PROTOCOL_VERSION;
    buf[2] = (payloadType >>  8) & 0xFF;
    buf[3] =  payloadType        & 0xFF;
    buf[4] = (payloadLen  >> 24) & 0xFF;
    buf[5] = (payloadLen  >> 16) & 0xFF;
    buf[6] = (payloadLen  >>  8) & 0xFF;
    buf[7] =  payloadLen         & 0xFF;
}

/* Echo.c echoSend() 역할 */
static void DoIP_SendRaw(tcpPcb *tpcb, uint8 *buf, uint16 len)
{
    tcp_write(tpcb, buf, len, TCP_WRITE_FLAG_COPY);
    tcp_output(tpcb);
}

/*********************************************************************************************************************/
