/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*
 * \title TC375 FreeRTOS basic example
 * \abstract This example shows how to get started with using the AURIX(TM) FreeRTOS port
 * \description This example explores FreeRTOS scheduling on AURIX(TM) TC375 using one 500ms LED task
 *
 * \name iLLD_TC375_ADS_FreeRTOS_Basic
 * \version V1.0.0
 * \board AURIX TC375 lite Kit, KIT_A2G_TC375_LITE, TC37xTP_A-Step
 * \keywords AURIX, TC3XX, TC375, FreeRTOS, Blinky, Task, ERU, LED, Button, External Interrupt
 * \documents See README.md
 * \lastUpdated 2023-04-27
 *********************************************************************************************************************/

#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort.h"
#include "_PinMap/IfxPort_PinMap.h"

#include "FreeRTOS.h"
#include "task.h"

#include "App_Eth/App_Eth.h"
#include "App_Someip/App_Someip.h"
#include "App_InfoService/App_InfoService.h"
#include "App_Can/App_Can.h"
#include "App_AebService/App_AebService.h"
#include "App_DriveService/App_DriveService.h"
#include "App_SensorService/App_SensorService.h"
#include "App_OtaGateway/App_OtaGateway.h"
#include "App_OtaReceiver/App_OtaReceiver.h"
#include "App_SensorOtaGateway/App_SensorOtaGateway_Doip.h"

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

#define LED_500MS_PIN (&IfxPort_P00_6)

#define SENSOR_OTA_DOIP_INIT_DELAY_MS      2000U
#define SENSOR_OTA_DOIP_TASK_STACK_SIZE    (configMINIMAL_STACK_SIZE + 256U)
#define SENSOR_OTA_DOIP_TASK_PRIORITY      (tskIDLE_PRIORITY + 1U)

static void init_led_pin(const IfxPort_Pin *pin);
static void task_app_led_500ms(void *arg);
static void task_sensor_ota_doip_init(void *arg);

static void app_assert_pass(BaseType_t result);
static void app_panic_loop(void);

volatile uint32_t g_mainBeforeScheduler = 0U;
volatile uint32_t g_mainAfterScheduler  = 0U;

volatile size_t g_mainFreeHeapBeforeScheduler = 0U;

/* Sensor OTA DoIP init task debug */
volatile uint32_t g_mainSensorOtaDoipInitTaskCreateCount = 0U;
volatile uint32_t g_mainSensorOtaDoipInitTaskRunCount = 0U;
volatile uint32_t g_mainSensorOtaDoipInitTaskDoneCount = 0U;

void core0_main(void)
{
    IfxCpu_enableInterrupts();

    /*
     * !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required.
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /*
     * Wait for CPU sync event
     */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    /*
     * 스케줄링 정상 확인용 LED 토글 태스크 등록
     */
    app_assert_pass(xTaskCreate(task_app_led_500ms,
                                "APP LED",
                                configMINIMAL_STACK_SIZE,
                                NULL,
                                0,
                                NULL));

    /*
     * CAN / Sensor ECU OTA Gateway 내부 경로 초기화
     *
     * 순서 중요:
     *  1. AppCan_Start()
     *  2. AppOtaGateway_Start()
     *  3. AppOtaReceiver_Init()
     */
    app_assert_pass(AppCan_Start());
    app_assert_pass(AppOtaGateway_Start());
    AppOtaReceiver_Init();

    /*
     * 기존 Application Services 시작
     */
    app_assert_pass(AppAebService_Start());
    app_assert_pass(AppDriveService_Start());

    /*
     * Ethernet / SOMEIP 계층 시작
     *
     * 주의:
     *  - AppEth_Start()가 task만 만들고 실제 lwIP/TCP stack 준비는 scheduler 이후에 될 수 있다.
     *  - 따라서 AppSensorOtaGatewayDoip_Init()는 여기서 직접 호출하지 않는다.
     *  - 아래 task_sensor_ota_doip_init()에서 scheduler 시작 후 delay를 주고 호출한다.
     */
    app_assert_pass(AppEth_Start());
    app_assert_pass(AppSomeip_Start());
    app_assert_pass(AppInfoService_Start());
    app_assert_pass(AppSensorService_Start());

    /*
     * Sensor ECU OTA Gateway DoIP init task 생성
     *
     * scheduler 시작 후 2초 기다린 다음 AppSensorOtaGatewayDoip_Init() 호출.
     * tcp_new/tcp_bind 시점이 너무 빨라서 실패하는 문제를 피하기 위함.
     */
    app_assert_pass(xTaskCreate(task_sensor_ota_doip_init,
                                "SENSOR OTA DOIP",
                                SENSOR_OTA_DOIP_TASK_STACK_SIZE,
                                NULL,
                                SENSOR_OTA_DOIP_TASK_PRIORITY,
                                NULL));

    g_mainSensorOtaDoipInitTaskCreateCount++;

    g_mainFreeHeapBeforeScheduler = xPortGetFreeHeapSize();

    g_mainBeforeScheduler = 1U;

    /*
     * Start the scheduler
     */
    vTaskStartScheduler();

    /*
     * 여기로 오면 scheduler 시작 실패.
     */
    app_panic_loop();

#if 0
    g_mainAfterScheduler = 1U;

    while (1)
    {
    }
#endif
}

/*
 * Required FreeRTOS callback, called in case of a stack overflow.
 * For the sake of simplicity, this function will loop indefinitely
 * and the root cause can be confirmed by using a debugger.
 */
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    (void)xTask;
    (void)pcTaskName;

    app_panic_loop();
}

void vApplicationMallocFailedHook(void)
{
    app_panic_loop();
}

static void init_led_pin(const IfxPort_Pin *pin)
{
    IfxPort_setPinHigh(pin->port, pin->pinIndex);
    IfxPort_setPinModeOutput(pin->port,
                             pin->pinIndex,
                             IfxPort_OutputMode_pushPull,
                             IfxPort_OutputIdx_general);
}

static void task_app_led_500ms(void *arg)
{
    (void)arg;

    init_led_pin(LED_500MS_PIN);

    while (1)
    {
        IfxPort_togglePin(LED_500MS_PIN->port, LED_500MS_PIN->pinIndex);
        vTaskDelay(pdMS_TO_TICKS(500U));
    }
}

static void task_sensor_ota_doip_init(void *arg)
{
    (void)arg;

    g_mainSensorOtaDoipInitTaskRunCount++;

    /*
     * AppEth_Start() 이후 실제 lwIP/TCP stack이 준비될 시간을 준다.
     *
     * 이전 문제:
     *  - core0_main()에서 scheduler 시작 전에 AppSensorOtaGatewayDoip_Init() 호출
     *  - g_sensorOtaDoipInitCount = 1
     *  - g_sensorOtaDoipBindOkCount = 0
     *  - g_sensorOtaDoipBindFailCount = 1
     *
     * 기대:
     *  - scheduler 시작 후 delay
     *  - tcp_new/tcp_bind 성공
     *  - g_sensorOtaDoipBindOkCount = 1
     */
    vTaskDelay(pdMS_TO_TICKS(SENSOR_OTA_DOIP_INIT_DELAY_MS));

    AppSensorOtaGatewayDoip_Init();

    g_mainSensorOtaDoipInitTaskDoneCount++;

    /*
     * DoIP init은 1회만 수행하면 되므로 task 종료.
     */
    vTaskDelete(NULL);
}

static void app_assert_pass(BaseType_t result)
{
    if(result != pdPASS)
    {
        app_panic_loop();
    }
}

static void app_panic_loop(void)
{
    while (1)
    {
        __nop();
    }
}
