/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
  *********************************************************************************************************************/
 /*\title TC375 FreeRTOS basic example
 * \abstract This example shows how to get started with using the AURIX(TM) FreeRTOS port
 * \description This example explores FreeRTOS scheduling on AURIX(TM) TC375 using one 500ms LED task
 *
 * \name iLLD_TC375_ADS_FreeRTOS_Basic
 * \version V1.0.0
 * \board AURIX TC375 lite Kit, KIT_A2G_TC375_LITE, TC37xTP_A-Step
 * \keywords AURIX, TC3XX, TC375, FreeRTOS, Blinky, Task, ERU, LED, Button, External Interrupt
 * \documents See README.md
 * \lastUpdated 2023-04-27
 *********************************************************************************************************************/
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort.h"
#include "_PinMap/IfxPort_PinMap.h"

#include "FreeRTOS.h"
#include "task.h"

#include "App_Eth/App_Eth.h"
#include "App_Someip/App_Someip.h"
#include "App_InfoService/App_InfoService.h"
#include "App_Can/App_Can.h"
#include "App_AebService/App_AebService.h"
#include "App_DriveService/App_DriveService.h"
#include "App_SensorService/App_SensorService.h"
#include "App_DoIP/App_DoIP.h"
#include "App_Flash/App_Flash.h"
#include "App_Sota/App_Sota.h"
#include "App_Uds/App_Uds.h"
#include "App_Debug/App_Debug.h"

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

#define LED_500MS_PIN (&IfxPort_P00_6)
#define APP_FRONTZCU_VERSION "1.0.0"

static void init_led_pin(const IfxPort_Pin *pin);
static void task_app_led_500ms(void *arg);
static void app_assert_pass(BaseType_t result);
static void app_panic_loop(void);

const char *App_GetFrontZcuVersion(void)
{
    return APP_FRONTZCU_VERSION;
}

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* SOTA 초기화: SWAPEN disabled이면 next entry에 Bank A marker를 기록하고 SWAPEN enable 후 reset */
    SOTA_InitialSetup();
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    /* 스케줄링 정상 확인용 LED 토글 태스크 등록 */
    app_assert_pass(xTaskCreate(task_app_led_500ms, "APP LED", configMINIMAL_STACK_SIZE, NULL, 0, NULL));

    app_assert_pass(AppCan_Start());
    app_assert_pass(AppAebService_Start());
    app_assert_pass(AppDriveService_Start());
    app_assert_pass(AppEth_Start());
    app_assert_pass(AppSomeip_Start());
    app_assert_pass(AppInfoService_Start());
    app_assert_pass(AppSensorService_Start());
    app_assert_pass(xTaskCreate(AppUds_Task,
                       "APP UDS",
                       APP_UDS_TASK_STACK_SIZE,
                       NULL,
                       APP_UDS_TASK_PRIORITY,
                       NULL));
    AppDebug_Init();    

    /* Start the scheduler */
    vTaskStartScheduler();

    app_panic_loop();
}

/* Required FreeRTOS callback, called in case of a stack overflow.
 * For the sake of simplicity, this function will loop indefinitely
 * and the root cause can be confirmed by using a debugger
 */
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    (void)xTask;
    (void)pcTaskName;

    AppDebug_Print("STACK OVERFLOW: %s", pcTaskName);

    app_panic_loop();
}

void vApplicationMallocFailedHook(void)
{
    app_panic_loop();
}

static void init_led_pin(const IfxPort_Pin *pin)
{
    IfxPort_setPinHigh(pin->port, pin->pinIndex);
    IfxPort_setPinModeOutput(pin->port, pin->pinIndex, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
}

static void task_app_led_500ms(void *arg)
{
    (void)arg;

    init_led_pin(LED_500MS_PIN);

    while (1)
    {
        IfxPort_togglePin(LED_500MS_PIN->port, LED_500MS_PIN->pinIndex);
        vTaskDelay(pdMS_TO_TICKS(500U));
        // vTaskDelay(pdMS_TO_TICKS(50U));
    }
}

static void app_assert_pass(BaseType_t result)
{
    if(result != pdPASS)
    {
        app_panic_loop();
    }
}

static void app_panic_loop(void)
{
    while (1)
    {
        __nop();
    }
}
